config/routes.rb
Rails.application.routes.draw do
  
  resources :scheduled_inspections do 
    member do 
      get :apply_extention
      patch :save_extention
      get :cancel_extention
      get :create_techlog
      get :defer_inspection
      get :check_status
      get :restart_techlogs
    end    
  end
  resources :autherization_codes do 
    collection do 
      get 'get_codes'
      get :autocomplete_codes
      post :import
      get :upload
    end
  end
  # resources :scheduled_inspections
  resources :inspections do 
    resources :work_packages do
      collection do
        post :import
        get :upload        
      end
    end
  end
  resources :tools do
    collection do
      post :import
      get :autocomplete
      get :serail_autocomplete
    end
  end
  resources :reports do 
    collection do      
      get :airframe      
      get :airframe_pdf      
      get :inspection_record_pdf      
      get :inspection_pdf      
      get :tyre_record_pdf      
      get :history_pdf      
      get :techlog_pdf      
      
    end
  end
  resources :flying_plans
  resources :requested_tools
  resources :part_items
  resources :parts do
    collection do
      post :import
      get :upload
      get :autocomplete
      get :autocomplete_serial
    end
  end
  resources :non_flying_days
  resources :limitation_logs do 
    member do
      get 'pdf'
    end
  end
  resources :addl_logs do 
    member do
      get 'pdf'
    end
  end
  resources :technical_orders do 
    collection do      
      get :history      
    end
    resources :changes
    
  end
  resources :techlogs do 
    member do
      get 'create_addl_log'
      get 'create_limitation_log'
      get 'create_techlog'
      get 'pdf'
      get 'approve_extension'
    end
  end
  resources :work_unit_codes do 
    collection do 
      get 'get_work_unit_codes'
      get :autocomplete_codes
      post :import
      get :upload
    end
  end
  resources :flying_logs do 
    member do
      get 'pdf'
      get 'cancel'
      get 'update_timing'
      get 'release'
      get 'get_history'
    end
  end
  root 'flying_logs#index'
  resources :aircrafts  do 
    collection do 
      get 'get_aircrafts'      
      get 'summary'      
      get 'report'      
    end
    member do 
      post :import
      get :upload
    end
  end
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  mount ActionCable.server => '/cable'

end

app/models/aircraft.rb
class Aircraft
  include Mongoid::Document
  include Mongoid::Timestamps

  field :number, type: Integer
  field :tail_number, type: String
  field :serial_no, type: String
  
  field :fuel_capacity, type: Float, default: 0
  field :oil_capacity, type: Float, default: 0
  
  field :type_model, type: String
  field :type_series, type: String

  field :organization, type: String

  field :available_for_flight, type: Mongoid::Boolean
  
  field :flight_hours, type: Float, default: 0
  field :engine_hours, type: Float, default: 0
  field :prop_hours, type: Float, default: 0
  field :landings, type: Integer, default: 0


  validates :tail_number, presence: true
  validates :serial_no, presence: true
  validates :fuel_capacity, presence: true
  validates :oil_capacity, presence: true
  validates_uniqueness_of :tail_number

  scope :active, -> { where(:id.in => FlyingPlan.where(is_flying: true).where(flying_date: Time.zone.now.strftime("%Y-%m-%d")).first.aircrafts.map(&:id)) }
  

  has_many :flying_logs, dependent: :destroy
  has_many :techlogs, dependent: :destroy
  has_many :part_items, dependent: :destroy
  has_many :part_histories, dependent: :destroy
  has_many :flying_histories, dependent: :destroy
  has_many :landing_histories, dependent: :destroy
  has_many :scheduled_inspections, as: :inspectable

  accepts_nested_attributes_for :part_items, :allow_destroy => true  
    
  def update_part_values flying_log
    self.flight_hours = flying_log.aircraft_total_time.corrected_total_aircraft_hours.to_f
    self.landings     = flying_log.aircraft_total_time.corrected_total_landings.to_f
    self.engine_hours = flying_log.aircraft_total_time.corrected_total_engine_hours.to_f
    self.prop_hours   = flying_log.aircraft_total_time.corrected_total_prop_hours.to_f
    self.save
    self.scheduled_inspections.not_completed.each do |scheduled_inspection|
      scheduled_inspection.update_scheduled_inspections self.flight_hours      
    end
    lifed_parts = self.part_items.lifed    
    lifed_parts.each do |part|            
      part.create_history_with_flying_log flying_log
    end    
    tyre_parts = self.part_items.tyre
    tyre_parts.each do |part|
      part.create_history_with_flying_log flying_log
    end    
  end

  def create_engine_history type, other_aircraft = nil, part = nil
    previous_history = self.flying_histories.last
    history = FlyingHistory.new 
    history.aircraft              = self
    history.this_aircraft_hours   = 0
    history.total_aircraft_hours  = previous_history.total_aircraft_hours

    history.this_engine_hours     = 0
    

    history.this_prop_hours       = 0
    history.total_prop_hours      = previous_history.total_prop_hours

    history.total_landings  = previous_history.total_landings    
    history.touch_go        = 0
    history.full_stop       = 0
    if type == 'removed'
      history.remarks = "Engine removed and installed to #{other_aircraft}."
      history.total_engine_hours    = 0
    else      
      history.total_engine_hours    = part.completed_hours if part.present? 
      if other_aircraft.present?
        history.remarks = "New Engine installed from #{other_aircraft}."
      else
        history.remarks = "New Engine installed."
      end
    end
    history.save!
  end
  def import file
    xlsx = Roo::Spreadsheet.open(file, extension: :xlsx)
    (4..xlsx.last_row).each do |i|
      row               = xlsx.row(i)      
      aircraft          = self
      # puts row.inspect
      # puts row[Part::AIRCRAFT_PART_LAST_HOUR_INSP].inspect
      # puts row[Part::AIRCRAFT_PART_LANDINGS].inspect
      # next;
      number     = row[Part::AIRCRAFT_PART_NUMBER].to_s.gsub("\n", '')
      noun       = row[Part::AIRCRAFT_PART_NOUN]
      trade      = row[Part::AIRCRAFT_PART_TRADE].downcase
      # formulate inspection 
      inspection_hours  = (row[Part::AIRCRAFT_PART_INSP_HOUR].present?) ? row[Part::AIRCRAFT_PART_INSP_HOUR].downcase.gsub("hrs",'').strip.to_i : nil
      inspection_calender_value = nil
      if row[Part::AIRCRAFT_PART_INSP_CALENDER].present?
        if row[Part::AIRCRAFT_PART_INSP_CALENDER].downcase.count('y') > 0
          inspection_calender_value = row[Part::AIRCRAFT_PART_INSP_CALENDER].downcase.gsub("year",'').strip.to_i
          inspection_duration = 2
        else
          inspection_calender_value = row[Part::AIRCRAFT_PART_INSP_CALENDER].downcase.gsub("month",'').strip.to_i
          inspection_duration = 1
        end
      end

      # formulate life
      lifed_calender_value   = nil
      if row[Part::AIRCRAFT_PART_LIFE_CALENDER].present?
        if row[Part::AIRCRAFT_PART_LIFE_CALENDER].downcase.count('y') > 0
          lifed_calender_value = row[Part::AIRCRAFT_PART_LIFE_CALENDER].downcase.gsub("year",'').strip.to_i
          lifed_duration = 2
        else
          lifed_calender_value = row[Part::AIRCRAFT_PART_LIFE_CALENDER].downcase.gsub("month",'').strip.to_i
          lifed_duration = 1
        end
      end      
      lifed_hours  = (row[Part::AIRCRAFT_PART_LIFE_HOUR].present?) ? row[Part::AIRCRAFT_PART_LIFE_HOUR].downcase.gsub("hrs",'').strip.to_f : 0

      # manufactoring or installing date 
      if row[Part::AIRCRAFT_PART_INSTALLED_DATE].present?
        if row[Part::AIRCRAFT_PART_INSTALLED_DATE].is_a? Date        
          installed_date      = DateTime.strptime(row[Part::AIRCRAFT_PART_INSTALLED_DATE].to_s, '%Y-%m-%d')
        else
          installed_date      = DateTime.strptime(row[Part::AIRCRAFT_PART_INSTALLED_DATE].to_s, '%m/%d/%Y')
        end
        if !installed_date.is_a? Date
          puts 'installed date is not a date'
        end
      end

      if row[Part::AIRCRAFT_PART_MANU_DATE].present?
        if row[Part::AIRCRAFT_PART_MANU_DATE].is_a? Date        
          manufacturing_date      = DateTime.strptime(row[Part::AIRCRAFT_PART_MANU_DATE].to_s, '%Y-%m-%d')
        else
          manufacturing_date      = DateTime.strptime(row[Part::AIRCRAFT_PART_MANU_DATE].to_s, '%m/%d/%Y')
        end
        if !manufacturing_date.is_a? Date
          puts 'manufacturing date is not a date'
        end
      end
      
      if manufacturing_date.present?
        track_from = :manufacturing_date
      elsif installed_date.present?
        track_from = :installation_date
      else
        track_from = :no_track
      end

      
            
      landings_completed  = nil
      if row[Part::AIRCRAFT_PART_LANDINGS].present?
        landings_completed  = row[Part::AIRCRAFT_PART_LANDINGS].to_i
      end

      serial_no           = row[Part::AIRCRAFT_PART_SERIAL_NO]
      is_serialized = false
      if serial_no.present?
        is_serialized = true        
      end
      last_inspection_date = nil
      if row[Part::AIRCRAFT_PART_LAST_CALANDER_INSP].present?        
        if row[Part::AIRCRAFT_PART_LAST_CALANDER_INSP].is_a? Date        
          last_inspection_date = DateTime.strptime(row[Part::AIRCRAFT_PART_LAST_CALANDER_INSP].to_s, '%Y-%m-%d')
        else
          puts row[Part::AIRCRAFT_PART_LAST_CALANDER_INSP].inspect
          last_inspection_date = DateTime.strptime(row[Part::AIRCRAFT_PART_LAST_CALANDER_INSP].to_s, '%m/%d/%Y')
        end
        if !last_inspection_date.is_a? Date
          puts 'installed date is not a date'
        end
      end
      completed_hours_when_installed = nil      
      completed_hours_when_installed = (row[Part::AIRCRAFT_PART_COMP_HOURS].present?) ? row[Part::AIRCRAFT_PART_COMP_HOURS].to_s.downcase.gsub("hrs",'').strip.to_f : 0

      aircraft_installation_hours = 0
      remaining_hours     = 
      install_hour = (row[Part::AIRCRAFT_PART_INSTALL_HOUR].present?) ? row[Part::AIRCRAFT_PART_INSTALL_HOUR].to_s.downcase.gsub("hrs",'').strip.to_f : 0
      
      completed_hours     = ((self.flight_hours.to_f - install_hour.to_f) + completed_hours_when_installed.to_f).round(2)
      aircraft_installation_hours = install_hour.to_f

      
      # if install_hour.present? and install_hour > 0
        
      # else
      #   completed_hours     = (self.flight_hours.to_f).round(2)
      # end

      
      
      part = Part.where(number: number).first
      if part.blank?
        part_data = {                        
          trade: trade,             
          number: number,                         
          noun: noun,                                     
          track_from: track_from,                                     

          inspection_duration: inspection_duration, 
          inspection_hours: inspection_hours, 
          inspection_calender_value: inspection_calender_value,

          lifed_duration: lifed_duration,
          lifed_calender_value: lifed_calender_value,
          lifed_hours: lifed_hours,
          is_serialized: is_serialized,
        }   
        part = Part.create!(part_data)
      end

      if number == 'ENPL-RT10227' 
        category = :engine
      elsif number == 'HC-C2YK-1BF I/L C2K00180'
        category = :propeller
      elsif noun == 'MAIN WHEEL LT'
        category = :left_tyre
      elsif noun == 'MAIN WHEEL RT'
        category = :right_tyre
      elsif noun == 'NOSE WHEEL'
        category = :nose_tail
      elsif number == '6127279-067'
        category = :battery
      end

      part_item_data = {
        part_id: part.id,
        aircraft_id: self.id,             
        serial_no: serial_no, 
        completed_hours: completed_hours,
        installed_date: installed_date,
        manufacturing_date: manufacturing_date,
        landings_completed: landings_completed,        
        last_inspection_date: last_inspection_date,        
        aircraft_installation_hours: aircraft_installation_hours,
        completed_hours_when_installed: completed_hours_when_installed,
        category: category
      }            
      if serial_no.present?
        part_item = PartItem.where(part_id: part.id).where(serial_no: serial_no).first
      else

app/models/flying_plan.rb
class FlyingPlan
  include Mongoid::Document
  include Mongoid::Timestamps

  field :flying_date, type: Date
  field :reason, type: String
  field :is_flying, type: Mongoid::Boolean

  has_and_belongs_to_many :aircrafts

  validate :due_inspections
  def due_inspections    
    due_inspection = nil
    aircrafts.each do |aircraft|
      aircraft.check_inspections
      if aircraft.scheduled_inspections.due.count > 0
        due_inspection = aircraft
      end
      if aircraft.part_items.map{|part| part if part.scheduled_inspections.due.count > 0}.reject(&:blank?).count > 0
        due_inspection = aircraft
      end
    end
    
    if due_inspection.present?
      errors.add(:flying_date, " #{due_inspection.tail_number} has due inspections.")
    end
  end
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  load_and_authorize_resource
  before_action :set_aircraft, only: [:show, :edit, :update, :destroy, :import, :upload]
  

  # GET /aircrafts
  # GET /aircrafts.json
  def index
    @aircrafts = Aircraft.all.order(tail_number: :asc)
  end

  # GET /aircrafts/1
  # GET /aircrafts/1.json
  def show
  end

  # GET /aircrafts/new
  def new
    @aircraft = Aircraft.new
  end

  # GET /aircrafts/1/edit
  def edit
  end

  # POST /aircrafts
  # POST /aircrafts.json
  def create
    @aircraft = Aircraft.new(aircraft_params)

    respond_to do |format|
      if @aircraft.save
        format.html { redirect_to @aircraft, notice: 'Aircraft was successfully created.' }
        format.json { render :show, status: :created, location: @aircraft }
      else
        format.html { render :new }
        format.json { render json: @aircraft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aircrafts/1
  # PATCH/PUT /aircrafts/1.json
  def update
    respond_to do |format|
      if @aircraft.update(aircraft_params)
        format.html { redirect_to @aircraft, notice: 'Aircraft was successfully updated.' }
        format.json { render :show, status: :ok, location: @aircraft }
      else
        puts @aircraft.errors.inspect
        format.html { render :edit }
        format.json { render json: @aircraft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aircrafts/1
  # DELETE /aircrafts/1.json
  def destroy
    @aircraft.destroy
    respond_to do |format|
      format.html { redirect_to aircrafts_url, notice: 'Aircraft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /aircrafts/get_aircrafts
  # GET /aircrafts/get_aircrafts.json
  def get_aircrafts
    search_string = params[:q]
    aircrafts = Aircraft.where(tail_number: /.*#{search_string}.*/i).limit(30)
    respond_to do |format|
      format.json { render json: { items: aircrafts.map { |a| { id: a.id.to_s, tail_number: a.tail_number } }, total_count: aircrafts.length, incomplete_results: false } }
    end
  end

  def upload
    
  end

  def import    
    @aircraft.import(params[:file_excel])    
    redirect_to @aircraft, notice: 'Parts imported.'
  end

  def summary
    
  end
  def report
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="daily_flying_report.xlsx"'
      }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aircraft
      @aircraft = Aircraft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aircraft_params
      params.require(:aircraft).permit(:tail_number, :serial_no, :fuel_capacity, :oil_capacity, :available_for_flight, :type_model, :type_series, :flight_hours, :engine_hours, :prop_hours, :landings)
    end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/views/aircrafts/_form.html.slim
= simple_form_for(@aircraft, html: { class: '' }) do |f|
  = f.error_notification
  .row
    .col-md-12
      .box.box-info
        .box-header.with-borderf
          h3.box-title
            i.fa.fa-bars
            | &nbsp; General
        .box-body
          - if can? :create, Aircraft
            .row
              .col-sm-6
                  = f.input :tail_number
              .col-sm-6
                = f.input :serial_no, label: 'Serail #'
            .row
              .col-sm-6
                = f.input :fuel_capacity
              .col-sm-6
                = f.input :oil_capacity
            .row
              .col-sm-6
                = f.input :type_model
              .col-sm-6
                = f.input :type_series
            .row
              .col-sm-6
                = f.input :flight_hours
              .col-sm-6
                = f.input :engine_hours
            .row
              .col-sm-6
                = f.input :prop_hours
              .col-sm-6
                = f.input :landings
          
  == render 'common/form_action_buttons', options: { form: f, index_path: aircrafts_path}

app/views/aircrafts/_part_fields.html.slim
.row.nested-fields
  .col-sm-12
    .row
      .col-sm-3
        = f.input :number
      .col-sm-3
        = f.input :noun
      .col-sm-3
        = f.input :serial_no
      .col-sm-3
        = f.input :calender_life, input_html: { class: 'datepicker' }
    .row
      .col-sm-3
        = f.input :installed_date, input_html: { class: 'datepicker' }
      .col-sm-3
        = f.input :remaining_hours
      .col-sm-3
        = f.input :flight_hours
      .col-sm-3
        = f.input :no_of_landings

    .row
      .col-sm-9
        = f.input :is_lifed, as: :boolean, checked_value: 1, unchecked_value: 0
      .col-sm-3
        = link_to_remove_association f, class: 'btn btn-block btn-danger btn-flat' do
          i.fa.fa-trash
    hr

app/views/aircrafts/edit.html.slim
= content_for :box_heading do
  | Edit
  |   
  = @aircraft.tail_number
== render 'form'

app/views/aircrafts/index.html.slim
= content_for :box_heading do
  | Aircraft
- todays_flying_plan = FlyingPlan.where(flying_date: Time.zone.now.strftime("%d/%m/%Y")).first
.row
  .col-md-12
    .box.box-info
      .box-body
        table.table.table-bordered.table-striped.data-tabled
          thead
            tr
              th width='10%'
                | Number
              th width='10%'
                | Serial #
              th width='10%'
                | Hours
              th width='15%'
                | Engine Hours
              th width='10%'
                | Landings
              th width='25%' 
                | Status
              th width='15%'
                | Actions
          tbody
            - @aircrafts.each do |aircraft|
              tr
                td.table-row-center
                  = link_to aircraft.tail_number, aircraft_path(aircraft)
                td.table-row-center
                  = aircraft.serial_no
                td.table-row-center
                  = aircraft.flight_hours
                td.table-row-center
                  = aircraft.engine_hours
                td.table-row-center
                  = aircraft.landings
                td
                  
                  - if todays_flying_plan.present? and todays_flying_plan.aircraft_ids.include? aircraft.id
                    - last_flying_log = aircraft.flying_logs.last
                    - if last_flying_log.present?
                      = last_flying_log.show_text_status
                    - else 
                      | No Flying Log created.
                  - else
                    | Not Flying Today.
                td.text-center width='20%'
                  = link_to aircraft_path(aircraft), class: 'btn btn-success btn-flat ' do
                    i.fa.fa-eye
                  - if can? :update, aircraft
                    = link_to edit_aircraft_path(aircraft), class: 'btn btn-info btn-flat ' do
                      i.fa.fa-pencil
        .col-sm-4.col-sm-offset-4
          - if can? :generate_report, Aircraft
            /= link_to 'New Aircraft', new_aircraft_path, class: 'btn btn-block btn-primary btn-flat'
            = link_to 'Generate Aircraft Report', report_aircrafts_path(format: :xlsx), class: 'btn btn-block btn-primary btn-flat'
        .clearfix

app/views/aircrafts/new.html.slim
= content_for :box_heading do
  | New Aircraft
== render 'form'

app/views/aircrafts/show.html.slim
= content_for :box_heading do
  | Aircraft:&nbsp;
  = @aircraft.tail_number

.row
  .col-md-12
    .box.box-info
      .box-header.with-border
        .row
          .col-md-6
            h3.box-title
              i.fa.fa-bars
              | &nbsp; General          
              
      .box-body
        .row
          .col-sm-12
            table.table.table-inverse
              tbody                
                tr
                  th width="25%"
                    | Tail Number
                  td = @aircraft.tail_number
                  th width="25%"
                    | Serial #
                  td = @aircraft.serial_no
                tr
                  th width="25%"
                    | Fuel Capacity
                  td = @aircraft.fuel_capacity
                  th width="25%"
                    | Oil Capacity
                  td = @aircraft.oil_capacity
                tr
                  th width="25%"
                    | Flight hours
                  td = @aircraft.flight_hours
                  th width="25%"
                    | Engine Hours
                  td = @aircraft.engine_hours
                tr
                  th width="25%"
                    | Landings
                  td = @aircraft.landings
                  th width="25%"
                    | Prop Hours
                  td = @aircraft.prop_hours
.row
  .col-md-12
    .box.box-info
      .box-header.with-border
        .row
          .col-md-6
            h3.box-title
              i.fa.fa-bars
              | &nbsp; 781
      .box-body
        .row
          .col-sm-12
            /- if can? :view_781, Aircraft
            = link_to airframe_pdf_reports_path(aircraft: @aircraft), class: 'btn btn-info btn-flat', target: '_blank' 
              | &nbsp; 781J
            | &nbsp;
            - Part::trades.each do |trade,value|
              = link_to inspection_record_pdf_reports_path(aircraft: @aircraft, trade: trade), class: 'btn btn-info btn-flat', target: '_blank' 
                = trade.titleize
                | &nbsp; 781D
              | &nbsp;
            = link_to inspection_pdf_reports_path(aircraft: @aircraft), class: 'btn btn-info btn-flat', target: '_blank'                 
              | &nbsp; 781K
            | &nbsp;
            = link_to tyre_record_pdf_reports_path(aircraft: @aircraft), class: 'btn btn-info btn-flat', target: '_blank'                 
              | &nbsp; Tyre Landing Record
            | &nbsp;
            = link_to history_pdf_reports_path(aircraft: @aircraft), class: 'btn btn-info btn-flat', target: '_blank'                 
              | &nbsp; History
            | &nbsp;
- @scheduled_inspections = @aircraft.scheduled_inspections.scheduled_insp
== render "scheduled_inspections/table", options: { heading: "Aircraft Scheduled Inspections"}
- @scheduled_inspections = @aircraft.scheduled_inspections.pending
== render "scheduled_inspections/table", options: { heading: "Aircraft Pending Inspections"}
- @scheduled_inspections = @aircraft.scheduled_inspections.in_progress
== render "scheduled_inspections/table", options: { heading: "Aircraft In Progress Inspections"}
- @scheduled_inspections = @aircraft.scheduled_inspections.due
== render "scheduled_inspections/table", options: { heading: "Aircraft Due Inspections"}
- @scheduled_inspections = ScheduledInspection.where(inspectable_type: PartItem.name).in(inspectable_id: @aircraft.part_items.map(&:id)).pending
== render "scheduled_inspections/table", options: { heading: "Aircraft Parts Pending Inspections"}
- @scheduled_inspections = ScheduledInspection.where(inspectable_type: PartItem.name).in(inspectable_id: @aircraft.part_items.map(&:id)).in_progress
== render "scheduled_inspections/table", options: { heading: "Aircraft Parts in Progress Inspections"}
- @scheduled_inspections = ScheduledInspection.where(inspectable_type: PartItem.name).in(inspectable_id: @aircraft.part_items.map(&:id)).due
== render "scheduled_inspections/table", options: { heading: "Aircraft Parts Due Inspections"}
- @part_items = @aircraft.part_items
== render "part_items/table", options: { heading: "Aircraft Parts"}
              
        
        .clearfix
- if can? :update, Aircraft
  = render 'common/actions_buttons', back_path: aircrafts_path, edit_path: edit_aircraft_path(@aircraft)

app/views/aircrafts/upload.html.slim
= content_for :box_heading do
  | Upload Part Excel for  
  = @aircraft.tail_number
= simple_form_for(@aircraft, :url => import_aircraft_path, :method => :post, html: { multipart: true}) do |f|
  = f.error_notification
  .row
    .col-md-12
      .box.box-info
        .box-header.with-borderf
          h3.box-title
            i.fa.fa-bars
            | &nbsp; General
        .box-body
          .row
            .col-sm-6
              = file_field_tag :file_excel
              
            
  .row
    .col-sm-4
      = link_to parts_path, class: 'btn btn-block btn-primary btn-flat' do
        i.fa.fa-angle-double-left
        | &nbsp; Back
    
    .col-sm-4 class="col-sm-offset-4"
      = button_tag :submit, id: 'create_update_user', class: 'btn btn-block btn-success btn-flat' do
        i.fa.fa-refresh
        | Upload Excel