config/routes.rb
Rails.application.routes.draw do
  
  resources :scheduled_inspections do 
    member do 
      get :apply_extention
      patch :save_extention
      get :cancel_extention
      get :create_techlog
      get :defer_inspection
      get :check_status
      get :restart_techlogs
    end    
  end
  resources :autherization_codes do 
    collection do 
      get 'get_codes'
      get :autocomplete_codes
      post :import
      get :upload
    end
  end
  # resources :scheduled_inspections
  resources :inspections do 
    resources :work_packages do
      collection do
        post :import
        get :upload        
      end
    end
  end
  resources :tools do
    collection do
      post :import
      get :autocomplete
      get :serail_autocomplete
    end
  end
  resources :reports do 
    collection do      
      get :airframe      
      get :airframe_pdf      
      get :inspection_record_pdf      
      get :inspection_pdf      
      get :tyre_record_pdf      
      get :history_pdf      
      get :techlog_pdf      
      
    end
  end
  resources :flying_plans
  resources :requested_tools
  resources :part_items
  resources :parts do
    collection do
      post :import
      get :upload
      get :autocomplete
      get :autocomplete_serial
    end
  end
  resources :non_flying_days
  resources :limitation_logs do 
    member do
      get 'pdf'
    end
  end
  resources :addl_logs do 
    member do
      get 'pdf'
    end
  end
  resources :technical_orders do 
    collection do      
      get :history      
    end
    resources :changes
    
  end
  resources :techlogs do 
    member do
      get 'create_addl_log'
      get 'create_limitation_log'
      get 'create_techlog'
      get 'pdf'
      get 'approve_extension'
    end
  end
  resources :work_unit_codes do 
    collection do 
      get 'get_work_unit_codes'
      get :autocomplete_codes
      post :import
      get :upload
    end
  end
  resources :flying_logs do 
    member do
      get 'pdf'
      get 'cancel'
      get 'update_timing'
      get 'release'
      get 'get_history'
    end
  end
  root 'flying_logs#index'
  resources :aircrafts  do 
    collection do 
      get 'get_aircrafts'      
      get 'summary'      
      get 'report'      
    end
    member do 
      post :import
      get :upload
    end
  end
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  mount ActionCable.server => '/cable'

end

app/models/work_package.rb
class WorkPackage
  include Mongoid::Document
  include Mongoid::Timestamps

  field :description, type: String

  belongs_to :inspection
  belongs_to :autherization_code

  def self.import inspection, file
    xlsx = Roo::Spreadsheet.open(file, extension: :xlsx)
    (5..xlsx.last_row).each do |i|
      row               = xlsx.row(i) 
      description       = row[1]

      next if description.blank? or row[2].blank?

      autherization_code    = AutherizationCode.where(code: row[2]).first
      if autherization_code.blank?
        WorkPackage.create({
          inspection: inspection, 
          description: description, 
          autherization_code: autherization_code
        })
      end
      
      # break;
    end
  end
end

app/controllers/work_packages_controller.rb
class WorkPackagesController < ApplicationController
  before_action :set_inspection
  before_action :set_work_package, only: [:show, :edit, :update, :destroy]

  # GET /work_packages
  # GET /work_packages.json
  def index
    @work_packages = WorkPackage.all
  end

  # GET /work_packages/1
  # GET /work_packages/1.json
  def show
  end

  # GET /work_packages/new
  def new
    @work_package = WorkPackage.new
  end

  # GET /work_packages/1/edit
  def edit
  end

  # POST /work_packages
  # POST /work_packages.json
  def create
    @work_package = WorkPackage.new(work_package_params)
    @work_package.inspection = @inspection
    respond_to do |format|
      if @work_package.save
        format.html { redirect_to @inspection, notice: 'Work package was successfully created.' }
        format.json { render :show, status: :created, location: @work_package }
      else
        format.html { render :new }
        format.json { render json: @work_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_packages/1
  # PATCH/PUT /work_packages/1.json
  def update
    respond_to do |format|
      if @work_package.update(work_package_params)
        format.html { redirect_to @inspection, notice: 'Work package was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_package }
      else
        format.html { render :edit }
        format.json { render json: @work_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_packages/1
  # DELETE /work_packages/1.json
  def destroy
    @work_package.destroy
    respond_to do |format|
      format.html { redirect_to @inspection, notice: 'Work package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload
    
  end

  def import
    WorkPackage.import(@inspection, params[:file_excel])
    redirect_to @inspection, notice: 'Work Package imported.'
  end

  private
    def set_inspection
      @inspection = Inspection.find(params[:inspection_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_work_package
      @work_package = WorkPackage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_package_params
      params.require(:work_package).permit(:description, :autherization_code_id)      
    end
end

app/helpers/work_packages_helper.rb
module WorkPackagesHelper
end

app/views/work_packages/_form.html.slim
= simple_form_for([@inspection, @work_package], html: { class: '' }) do |f|
  = f.input :autherization_code_id, as: :hidden
  .row
    .col-md-12
      .box.box-info
        .box-header.with-borderf
          h3.box-title
            i.fa.fa-bars
            | &nbsp; General
        .box-body
          .row
            .col-sm-6
              = f.input :description
            .col-sm-6
              - if f.object.autherization_code.present?
                = f.input :autherization_code, :url => autocomplete_codes_autherization_codes_path, :as => :autocomplete, input_html: {id_element: "#work_package_autherization_code_id", value: f.object.autherization_code.code }
              - else 
                = f.input :autherization_code, :url => autocomplete_codes_autherization_codes_path, :as => :autocomplete, input_html: {id_element: "#work_package_autherization_code_id"}
              

  == render 'common/form_action_buttons', options: { form: f, index_path: inspection_path(@inspection)}

app/views/work_packages/_table.html.slim
.row
  .col-md-12
    .box.box-info
      .box-header.with-border
          .row
            .col-md-6
              h3.box-title
                i.fa.fa-bars
                | &nbsp; Work Packages
      .box-body
        table.table.table-bordered.table-striped.data-tabled
          thead
            tr                
              th width="50%"
                | Description
              th
                | Authorisation Code
              th 
                | Action
              
                
          tbody
            - @inspection.work_packages.each do |work_package|
              tr
                td.table-row-center
                  = work_package.description
                td.table-row-center
                  = work_package.autherization_code.inspection_type  
                td 
                  - if params[:controller] == "inspections"
                    = link_to edit_inspection_work_package_path(@inspection, work_package), class: 'btn btn-info btn-flat ' do
                      i.fa.fa-pencil
                    = link_to inspection_work_package_path(@inspection, work_package), data: {:confirm => 'Are you sure?'}, class: 'btn btn-danger btn-flat', :method => :delete do
                      i.fa.fa-trash        
        - if params[:controller] == "inspections"
          .row
            .col-sm-4.col-sm-offset-2
              = link_to 'Upload Work Package', upload_inspection_work_packages_path(@inspection), class: 'btn btn-block btn-primary btn-flat' 
            .col-sm-4
              = link_to 'Create Work Package Entry', new_inspection_work_package_path(@inspection), class: 'btn btn-block btn-primary btn-flat'
        .clearfix

app/views/work_packages/edit.html.slim
= content_for :box_heading do
  | Edit Work Package
== render 'form'

app/views/work_packages/index.html.slim
h1 Listing work_packages

table
  thead
    tr
      th
      th
      th

  tbody
    - @work_packages.each do |work_package|
      tr
        td = link_to 'Show', work_package
        td = link_to 'Edit', edit_work_package_path(work_package)
        td = link_to 'Destroy', work_package, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Work package', new_work_package_path

app/views/work_packages/new.html.slim
= content_for :box_heading do
  | New Work Package
== render 'form'

app/views/work_packages/show.html.slim
p#notice = notice


= link_to 'Edit', edit_work_package_path(@work_package)
'  |
= link_to 'Back', work_packages_path

app/views/work_packages/upload.html.slim
= content_for :box_heading do
  | Upload Work Package for 
  = @inspection.name
= simple_form_for(@inspection, :url => import_inspection_work_packages_path, :method => :post, html: { multipart: true}) do |f|
  = f.error_notification
  .row
    .col-md-12
      .box.box-info
        .box-header.with-borderf
          h3.box-title
            i.fa.fa-bars
            | &nbsp; General
        .box-body
          .row
            .col-sm-6
              = file_field_tag :file_excel
              
            
  .row
    .col-sm-4
      = link_to @inspection, class: 'btn btn-block btn-primary btn-flat' do
        i.fa.fa-angle-double-left
        | &nbsp; Back
    
    .col-sm-4 class="col-sm-offset-4"
      = button_tag :submit, id: 'create_update_user', class: 'btn btn-block btn-success btn-flat' do
        i.fa.fa-refresh
        | Upload Excel