config/routes.rb
Rails.application.routes.draw do
  
  resources :scheduled_inspections do 
    member do 
      get :apply_extention
      patch :save_extention
      get :cancel_extention
      get :create_techlog
      get :defer_inspection
      get :check_status
      get :restart_techlogs
    end    
  end
  resources :autherization_codes do 
    collection do 
      get 'get_codes'
      get :autocomplete_codes
      post :import
      get :upload
    end
  end
  # resources :scheduled_inspections
  resources :inspections do 
    resources :work_packages do
      collection do
        post :import
        get :upload        
      end
    end
  end
  resources :tools do
    collection do
      post :import
      get :autocomplete
      get :serail_autocomplete
    end
  end
  resources :reports do 
    collection do      
      get :airframe      
      get :airframe_pdf      
      get :inspection_record_pdf      
      get :inspection_pdf      
      get :tyre_record_pdf      
      get :history_pdf      
      get :techlog_pdf      
      
    end
  end
  resources :flying_plans
  resources :requested_tools
  resources :part_items
  resources :parts do
    collection do
      post :import
      get :upload
      get :autocomplete
      get :autocomplete_serial
    end
  end
  resources :non_flying_days
  resources :limitation_logs do 
    member do
      get 'pdf'
    end
  end
  resources :addl_logs do 
    member do
      get 'pdf'
    end
  end
  resources :technical_orders do 
    collection do      
      get :history      
    end
    resources :changes
    
  end
  resources :techlogs do 
    member do
      get 'create_addl_log'
      get 'create_limitation_log'
      get 'create_techlog'
      get 'pdf'
      get 'approve_extension'
    end
  end
  resources :work_unit_codes do 
    collection do 
      get 'get_work_unit_codes'
      get :autocomplete_codes
      post :import
      get :upload
    end
  end
  resources :flying_logs do 
    member do
      get 'pdf'
      get 'cancel'
      get 'update_timing'
      get 'release'
      get 'get_history'
    end
  end
  root 'flying_logs#index'
  resources :aircrafts  do 
    collection do 
      get 'get_aircrafts'      
      get 'summary'      
      get 'report'      
    end
    member do 
      post :import
      get :upload
    end
  end
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  mount ActionCable.server => '/cable'

end

app/models/scheduled_inspection.rb
class ScheduledInspection
  include Mongoid::Document
  include Mongoid::Timestamps
  include SimpleEnum::Mongoid
  
  as_enum :status, scheduled: 0, pending: 1, in_progress: 2, completed: 3, due: 4
  as_enum :condition, normal: 0, extention_applied: 1, extention_granted: 2

  field :hours, type: Float, default: 0
  field :completed_hours, type: Float, default: 0
  field :calender_life_date, type: Date
  field :starting_date, type: Date
  field :inspection_started, type: Date
  field :inspection_completed, type: Date
  field :is_repeating, type: Mongoid::Boolean
  field :trade_cd, type: Integer
  field :kind_cd, type: Integer
  field :extention_hours, type: Integer
  field :extention_days, type: Integer
  field :aircraft_referenced_hours, type: Float
  
  belongs_to :inspection  
  belongs_to :started_by, :class_name => "User", optional: true
  belongs_to :inspectable, polymorphic: true

  has_one :techlog

  scope :scheduled_insp, -> { where(status_cd: 0)}
  scope :not_completed, -> { ne(status_cd: 3)}
  scope :in_progress, -> { where(status_cd: 2)}
  scope :completed, -> { where(status_cd: 3)}
  scope :due, -> { where(status_cd: 4)}
  scope :pending, -> { where(status_cd: 1)}
  scope :pending_n_due, -> { any_of({status_cd: 1}, {status_cd: 4})}
  scope :calender_based, -> { ne(calender_life_date: nil)}  
  
  validate :check_extention

  def check_extention
    if condition == :extention_applied
      if extention_hours == 0 and extention_days == 0
        errors.add(:extention_hours, " Please select at least one option.")
      end
      if extention_days.present? and extention_days > 0 and self.calender_life_date.blank?
        errors.add(:extention_days, " This inspection is not based on days.")
      end
      if extention_hours.present? and extention_hours > 0 and self.hours == 0
        errors.add(:extention_hours, " This inspection is not based on hours.")
      end
    end
  end

  before_create :set_normal
  after_update :start_work_package

  def set_normal
    self.condition_cd = 0    
  end

  def start_work_package    
    if (status_was == :scheduled or status_was == :pending or status_was == :due) and status == :in_progress
      self.start_inspection
    end
    if condition_cd_was == 0 and condition_cd == 1
      if inspectable_type == Aircraft.name
        inspectable_name = inspectable.tail_number
        aircraft_id = inspectable.id
      else
        inspectable_name = inspectable.part.number        
        aircraft_id = inspectable.aircraft_id
      end
      log = Techlog.create!({type_cd: 2, condition_cd: 0, 
          log_time: "#{Time.zone.now.strftime("%H:%M %p")}",
          description: "Extention Applied for #{self.inspection.name}", 
          user_id: self.started_by_id, log_date: "#{Time.zone.now.strftime("%Y-%m-%d")}", 
          aircraft_id: aircraft_id, dms_version: System.first.settings['dms_version_number'],
          scheduled_inspection_id: self.id, is_extention_applied: true
        })
    end    
  end

  def start_inspection
    if inspectable_type == Aircraft.name
      inspectable_name = inspectable.tail_number
      aircraft_id = inspectable.id
    else
      inspectable_name = inspectable.part.number        
      aircraft_id = inspectable.aircraft_id
    end
    parent_log = Techlog.create!({type_cd: 2, condition_cd: 2, log_time: "#{Time.zone.now.strftime("%H:%M %p")}", 
      description: "#{self.inspection.name} for #{inspectable_name}", 
      action: "#{self.inspection.name} for #{inspectable_name}", 
      user_id: self.started_by_id, log_date: "#{Time.zone.now.strftime("%Y-%m-%d")}", 
      aircraft_id: aircraft_id, dms_version: System.first.settings['dms_version_number'],
      scheduled_inspection_id: self.id
    })      
    self.inspection.work_packages.each do |work_package|        
      log = Techlog.create!({type_cd: 2, condition_cd: 0, 
        log_time: "#{Time.zone.now.strftime("%H:%M %p")}",
        description: work_package.description, autherization_code: work_package.autherization_code.id, 
        user_id: self.started_by_id, log_date: "#{Time.zone.now.strftime("%Y-%m-%d")}", 
        aircraft_id: aircraft_id, dms_version: System.first.settings['dms_version_number'],
        parent_techlog_id: parent_log.id
      })
    end
  end
  def complete_inspection
    self.status_cd = 3
    self.inspection_completed = Time.zone.now
    self.save
    if inspectable_type == Aircraft.name
      if self.inspection.is_repeating
        self.inspection.create_aircraft_inspection Aircraft.find inspectable_id
      end
    else
      if self.inspection.is_repeating
        part = PartItem.find inspectable_id
        part.last_inspection_date = Time.zone.now
        part.save!
        self.inspection.create_part_inspection part
      end
    end
  end
  def calculate_status    
    if self.hours.present? and self.hours > 0 and self.completed_hours.present?
      if (self.hours - self.completed_hours).to_f <= 0
        self.status = 4
      elsif (self.hours - self.completed_hours) < 10
        self.status = 1
      else
        self.status = 0
      end
    end
    if calender_life_date.present? 
      if calender_life_date.strftime('%Y-%m-%d').to_date <= (Time.zone.now).strftime('%Y-%m-%d').to_date
        self.status_cd = 4
      elsif calender_life_date.strftime('%Y-%m-%d') <= (Time.zone.now + 30.days).strftime('%Y-%m-%d')
        self.status_cd = 1
      else
        # self.status = 0
      end      
    end          
    self.save
  end
  def update_scheduled_inspections completed_hours    
    self.completed_hours = completed_hours.round(2)    
    self.save
    self.calculate_status
  end
  
end

app/controllers/scheduled_inspections_controller.rb
class ScheduledInspectionsController < ApplicationController
  before_action :set_scheduled_inspection, only: [:show, :edit, :update, :destroy, :apply_extention, :save_extention, :cancel_extention, :create_techlog, :defer_inspection, :check_status]

  # GET /scheduled_inspections
  # GET /scheduled_inspections.json
  def index
    if params[:type] == 'condition'
      @scheduled_inspections = ScheduledInspection.where(condition_cd: params[:condition].to_i).all
    else
      @scheduled_inspections = ScheduledInspection.where(status_cd: params[:status].to_i).all
    end
  end

  # GET /scheduled_inspections/1
  # GET /scheduled_inspections/1.json
  def show
  end
  
  def apply_extention
  end
  
  def save_extention    
    respond_to do |format|      
      @scheduled_inspection.condition_cd = 1
      if @scheduled_inspection.update(scheduled_inspection_params)
        format.html { redirect_to @scheduled_inspection, notice: 'Scheduled inspection was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduled_inspection }
      else
        format.html { render :apply_extention }
        format.json { render json: @scheduled_inspection.errors, status: :unprocessable_entity }
      end
    end    
  end

  def check_status
    @scheduled_inspection.calculate_status
    redirect_to @scheduled_inspection
  end

  def defer_inspection
    @scheduled_inspection.condition_cd = 0
    if @scheduled_inspection.inspection.no_of_hours.to_f > 0
      @scheduled_inspection.hours = @scheduled_inspection.completed_hours + @scheduled_inspection.inspection.no_of_hours
    end
    
    @scheduled_inspection.starting_date      = Time.zone.now
    @scheduled_inspection.calender_life_date = @scheduled_inspection.inspection.get_duration Time.zone.now
    @scheduled_inspection.save
    @scheduled_inspection.calculate_status
    redirect_to @scheduled_inspection, notice: 'Scheduled inspection extention was successfully defered.'
    
  end
  def cancel_extention
    if @scheduled_inspection.condition_cd == 1
      @scheduled_inspection.techlog.destroy if @scheduled_inspection.techlog.present?
      @scheduled_inspection.extention_days = 0
      @scheduled_inspection.extention_hours = 0
      @scheduled_inspection.condition_cd = 0
      @scheduled_inspection.save
      redirect_to @scheduled_inspection, notice: 'Scheduled inspection extention was successfully canceled.'
    end
  end

  def create_techlog
    if @scheduled_inspection.status_cd == 2 and @scheduled_inspection.techlog.blank?
      @scheduled_inspection.start_inspection      
      redirect_to @scheduled_inspection
    end
  end

  # GET /scheduled_inspections/new
  def new
    @scheduled_inspection = ScheduledInspection.new
  end

  # GET /scheduled_inspections/1/edit
  def edit
  end

  # POST /scheduled_inspections
  # POST /scheduled_inspections.json
  def create
    # @scheduled_inspection = ScheduledInspection.new(scheduled_inspection_params)

    respond_to do |format|
      if @scheduled_inspection.save
        format.html { redirect_to @scheduled_inspection, notice: 'Scheduled inspection was successfully created.' }
        format.json { render :show, status: :created, location: @scheduled_inspection }
      else
        format.html { render :new }
        format.json { render json: @scheduled_inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduled_inspections/1
  # PATCH/PUT /scheduled_inspections/1.json
  def update
    respond_to do |format|
      @scheduled_inspection.status_cd = 2
      if @scheduled_inspection.update(scheduled_inspection_params)
        format.html { redirect_to @scheduled_inspection, notice: 'Scheduled inspection was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduled_inspection }
      else
        format.html { render :edit }
        format.json { render json: @scheduled_inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_inspections/1
  # DELETE /scheduled_inspections/1.json
  def destroy
    @scheduled_inspection.destroy
    respond_to do |format|
      format.html { redirect_to scheduled_inspections_url, notice: 'Scheduled inspection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduled_inspection
      @scheduled_inspection = ScheduledInspection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduled_inspection_params
      # params.fetch(:scheduled_inspection, {})
      params.require(:scheduled_inspection).permit(:started_by_id, :inspection_started, :extention_hours, :extention_days)
    end
end

app/helpers/scheduled_inspections_helper.rb
module ScheduledInspectionsHelper
end

app/views/scheduled_inspections/_form.html.slim
= simple_form_for(@scheduled_inspection) do |f|  
  = f.error_notification
  - if @scheduled_inspection.errors.full_messages.count > 0
    .alert.alert-danger
      ul
        - @scheduled_inspection.errors.full_messages.each do |error_message|
          li
            = error_message
  == render "scheduled_inspections/show"                  
  /- if @scheduled_inspection.status_cd.to_i == 0 or @scheduled_inspection.status_cd.to_i == 1
  = f.input :started_by_id, as: :hidden, input_html: { value: current_user.id }
  = f.input :inspection_started, as: :hidden, input_html: { value: Time.zone.now }
  .row
    .col-sm-4
      = link_to inspection_path(@scheduled_inspection.inspection), class: 'btn btn-block btn-primary btn-flat' do
        i.fa.fa-angle-double-left
        | &nbsp; Back
    
    /- if can? :start_inspection, ScheduledInspection and (@scheduled_inspection.status_cd == 1 or @scheduled_inspection.status_cd == 4) and @scheduled_inspection.inspection.work_packages.count > 0
    - if can? :update, ScheduledInspection
      .col-sm-4 class="col-sm-offset-4"
        = f.button :submit, "Start Scheduled Inspection", class: 'btn btn-block btn-success btn-flat'
          
  
      
    
        

app/views/scheduled_inspections/_show.html.slim
.row
  .col-md-12
    .box.box-info
      .box-header.with-border
        .row
          .col-md-6
            h3.box-title
              i.fa.fa-bars
              | &nbsp; Inspection
          .col-md-6.text-right
            - if current_user.admin? and @scheduled_inspection.status_cd != 2 and @scheduled_inspection.status_cd != 3
              = link_to check_status_scheduled_inspection_path(@scheduled_inspection), class: 'btn btn-info btn-flat'
                i.fa.fa-pencil
                | &nbsp; Check Status
              | &nbsp;
            - if can? :defer_inspection, ScheduledInspection and @scheduled_inspection.status_cd == 4
              = link_to defer_inspection_scheduled_inspection_path(@scheduled_inspection), class: 'btn btn-info btn-flat'
                i.fa.fa-pencil
                | &nbsp; Defer Extention
              | &nbsp;
            - if can? :apply_extention, ScheduledInspection and @scheduled_inspection.condition_cd == 0 and (@scheduled_inspection.status_cd == 4)
              = link_to apply_extention_scheduled_inspection_path(@scheduled_inspection), class: 'btn btn-info btn-flat'
                i.fa.fa-pencil
                | &nbsp; Apply for Extention
              | &nbsp;
            - if can? :cancel_extention, ScheduledInspection and @scheduled_inspection.condition_cd == 1
              = link_to cancel_extention_scheduled_inspection_path(@scheduled_inspection), class: 'btn btn-info btn-flat'
                i.fa.fa-pencil
                | &nbsp; Cancel Extention
              | &nbsp;
            - if can? :start_inspection, ScheduledInspection and @scheduled_inspection.status_cd == 2 and @scheduled_inspection.techlog.blank?
              = link_to create_techlog_scheduled_inspection_path(@scheduled_inspection), class: 'btn btn-info btn-flat'
                i.fa.fa-pencil
                | &nbsp; Generate Techlogs
              | &nbsp;
            
      .box-body
        .row
          .col-sm-12
            table.table.table-inverse
              tbody                
                tr
                  th width="25%"
                    | Name
                  td = @scheduled_inspection.inspection.name
                  th width="25%"
                    | Hours Frequency
                  td = @scheduled_inspection.inspection.no_of_hours
                tr
                  th width="25%"
                    | Calender Frequency
                  td 
                    = @scheduled_inspection.inspection.calender_value
                    |   
                    = @scheduled_inspection.inspection.duration
                  th width="25%"
                  td
.row
  .col-md-12
    .box.box-info
      .box-header.with-border
        .row
          .col-md-6
            h3.box-title
              i.fa.fa-bars
              | &nbsp; Scheduled Inspection
          .col-sm-6.text-right
      .box-body
        .row
          .col-sm-12
            table.table.table-inverse
              tbody                
                tr
                  th width="25%"
                    | Item
                  td 
                    - if @scheduled_inspection.inspectable_type == Aircraft.name
                      = @scheduled_inspection.inspectable.tail_number
                    - else
                      = @scheduled_inspection.inspectable.part.number
                  th width="25%"
                    | Hours
                  td = @scheduled_inspection.hours
                tr
                  th width="25%"
                    | Calender Due
                  td 
                    = display_date @scheduled_inspection.calender_life_date                      
                  th width="25%"
                    | Hours Due
                  td
                    = @scheduled_inspection.hours
                tr
                  th width="25%"
                    | Current Date
                  td 
                    = display_date Time.zone.now
                  th width="25%"
                    | Completed Hours
                  td
                    = @scheduled_inspection.completed_hours.round(2)
                tr
                  th width="25%"
                    | Started At
                  td 
                    = display_date @scheduled_inspection.inspection_started
                  th width="25%"
                    | Completed Date
                  td
                    = display_date @scheduled_inspection.inspection_completed
                tr
                  th width="25%"
                    | Status
                  td 
                    = @scheduled_inspection.status
                  th width="25%"
                    
                  td
- @inspection = @scheduled_inspection.inspection
== render "work_packages/table"

app/views/scheduled_inspections/_table.html.slim
.row
  .col-md-12
    .box.box-info
      .box-header.with-border
          .row
            .col-md-6
              h3.box-title
                i.fa.fa-bars
                | &nbsp; 
                - if options.present? and options[:heading].present?
                  = options[:heading]
                - else
                  | Scheduled Inspections
      .box-body
        table.table.table-bordered.table-striped.data-tabled
          thead
            tr                
              th
                | Aircraft
              th
                | Inspection Item
              th
                | Inspection Name
              th
                | Due at Hours
              th
                | Due at Calender
              th
                | Status
              th
                | Hours Completed
              th
                | Action
              
                
          tbody
            - @scheduled_inspections.each do |scheduled_inspection|
              tr
                td.table-row-center
                  - if scheduled_inspection.inspectable_type.present?
                    - if scheduled_inspection.inspectable_type == Aircraft.name
                      = scheduled_inspection.inspectable.tail_number
                    - else                    
                      - if scheduled_inspection.inspectable.aircraft.present?
                        = scheduled_inspection.inspectable.aircraft.tail_number
                td.table-row-center
                  - if scheduled_inspection.inspectable_type == Aircraft.name
                    = scheduled_inspection.inspectable.tail_number
                  - else
                    = scheduled_inspection.inspectable.part.number
                td.table-row-center
                  = scheduled_inspection.inspection.name
                td.table-row-center
                  - if scheduled_inspection.hours.present?
                    = scheduled_inspection.hours.round(2)
                td.table-row-center
                  = display_date scheduled_inspection.calender_life_date
                  
                td.table-row-center
                  = scheduled_inspection.status
                td.table-row-center
                  = scheduled_inspection.completed_hours.round(2)
                td.table-row-center
                  - if scheduled_inspection.techlog.present?
                    = link_to techlog_path(scheduled_inspection.techlog), class: 'btn btn-success btn-flat ' do
                      i.fa.fa-file
                  = link_to scheduled_inspection_path(scheduled_inspection), class: 'btn btn-success btn-flat ' do
                    i.fa.fa-eye
                  - if scheduled_inspection.kind_cd != 0
                    = link_to edit_scheduled_inspection_path(scheduled_inspection), class: 'btn btn-info btn-flat ' do
                      i.fa.fa-star
                

      
        .clearfix

app/views/scheduled_inspections/apply_extention.html.slim
= content_for :box_heading do
  | Apply for Extention
= simple_form_for(@scheduled_inspection, :url => save_extention_scheduled_inspection_path) do |f|  
  = f.error_notification
  - if @scheduled_inspection.errors.full_messages.count > 0
    .alert.alert-danger
      ul
        - @scheduled_inspection.errors.full_messages.each do |error_message|
          li
            = error_message
  .row
    .col-md-12
      .box.box-info
        .box-header.with-border
          .row
            .col-md-6
              h3.box-title
                i.fa.fa-bars
                | &nbsp; Inspection

        .box-body
          .row
            .col-sm-12
              table.table.table-inverse
                tbody                
                  tr
                    th width="25%"
                      | Name
                    td = @scheduled_inspection.inspection.name
                    th width="25%"
                      | Hours Frequency
                    td = @scheduled_inspection.inspection.no_of_hours
                  tr
                    th width="25%"
                      | Calender Frequency
                    td 
                      = @scheduled_inspection.inspection.calender_value
                      |   
                      = @scheduled_inspection.inspection.duration
                    th width="25%"
                    td
  .row
    .col-md-12
      .box.box-info
        .box-header.with-border
          .row
            .col-md-6
              h3.box-title
                i.fa.fa-bars
                | &nbsp; Scheduled Inspection
            .col-sm-6.text-right            
              
                
        .box-body
          .row
            .col-sm-12
              table.table.table-inverse
                tbody                
                  tr
                    th width="25%"
                      | Item
                    td 
                      - if @scheduled_inspection.inspectable_type == Aircraft.name
                        = @scheduled_inspection.inspectable.tail_number
                      - else
                        = @scheduled_inspection.inspectable.part.number
                    th width="25%"
                      | Hours Frequency
                    td = @scheduled_inspection.inspection.no_of_hours
                  tr
                    th width="25%"
                      | Calender Due
                    td 
                      = display_date @scheduled_inspection.calender_life_date                      
                    th width="25%"
                      | Hours Due
                    td
                      = @scheduled_inspection.hours
                  tr
                    th width="25%"
                      | Current Date
                    td 
                      = display_date Time.zone.now
                    th width="25%"
                      | Completed Hours
                    td
                      = @scheduled_inspection.completed_hours
                  tr
                    th width="25%"
                      | Started At
                    td 
                      = display_date @scheduled_inspection.inspection_started
                    th width="25%"
                      | Completed Date
                    td
                      = display_date @scheduled_inspection.inspection_completed
                  tr
                    th width="25%"
                      | Status
                    td 
                      = @scheduled_inspection.status
                    th width="25%"
                      
                    td
  
  /.row
    .col-md-12
      .box.box-info
        .box-header.with-border
          .row
            .col-md-6
              h3.box-title
                i.fa.fa-bars
                | &nbsp; Scheduled Inspection
            .col-sm-6.text-right    

  .row
    .col-md-12
      .box.box-info
        .box-header.with-borderf
          h3.box-title
            i.fa.fa-bars
            | &nbsp;             
            | Expection Time
        .box-body
          .row
            - if @scheduled_inspection.hours.present? and @scheduled_inspection.hours > 0            
              .col-sm-6                            
                = f.input :extention_hours, collection: 0..10, include_blank: false       
            - if @scheduled_inspection.calender_life_date.present?
              .col-sm-6                            
                = f.input :extention_days, collection: 0..30, include_blank: false       
            = f.input :started_by_id, as: :hidden, input_html: { value: current_user.id }
  
  .row
    .col-sm-4
      = link_to inspection_path(@scheduled_inspection), class: 'btn btn-block btn-primary btn-flat' do
        i.fa.fa-angle-double-left
        | &nbsp; Back
    /- if @scheduled_inspection.condition_cd != 1 and @scheduled_inspection.status_cd != 2
    .col-sm-4 class="col-sm-offset-4"
      = f.button :submit, id: 'create_update_user', class: 'btn btn-block btn-success btn-flat' do
        i.fa.fa-refresh        
        | &nbsp; Apply for Extention
        
  /== render 'common/form_action_buttons', options: { form: f, index_path: inspection_path(@scheduled_inspection.inspection)}

app/views/scheduled_inspections/edit.html.slim
= content_for :box_heading do
  | Start Inspection
== render 'form'

app/views/scheduled_inspections/index.html.slim
= content_for :box_heading do
  | Scheduled Inpections

== render "scheduled_inspections/table", options: { heading: "Scheduled Inspections"}
                  
        

app/views/scheduled_inspections/new.html.slim
h1 New scheduled_inspection

== render 'form'

= link_to 'Back', scheduled_inspections_path

app/views/scheduled_inspections/show.html.slim
= content_for :box_heading do
  | Scheduled Inspection:&nbsp;
  = @scheduled_inspection.inspection.name
== render "scheduled_inspections/show"
- if can? :update, ScheduledInspection
  = render 'common/actions_buttons', back_path: scheduled_inspections_path()