config/routes.rb
Rails.application.routes.draw do
  
  resources :scheduled_inspections do 
    member do 
      get :apply_extention
      patch :save_extention
      get :cancel_extention
      get :create_techlog
      get :defer_inspection
      get :check_status
      get :restart_techlogs
    end    
  end
  resources :autherization_codes do 
    collection do 
      get 'get_codes'
      get :autocomplete_codes
      post :import
      get :upload
    end
  end
  # resources :scheduled_inspections
  resources :inspections do 
    resources :work_packages do
      collection do
        post :import
        get :upload        
      end
    end
  end
  resources :tools do
    collection do
      post :import
      get :autocomplete
      get :serail_autocomplete
    end
  end
  resources :reports do 
    collection do      
      get :airframe      
      get :airframe_pdf      
      get :inspection_record_pdf      
      get :inspection_pdf      
      get :tyre_record_pdf      
      get :history_pdf      
      get :techlog_pdf      
      
    end
  end
  resources :flying_plans
  resources :requested_tools
  resources :part_items
  resources :parts do
    collection do
      post :import
      get :upload
      get :autocomplete
      get :autocomplete_serial
    end
  end
  resources :non_flying_days
  resources :limitation_logs do 
    member do
      get 'pdf'
    end
  end
  resources :addl_logs do 
    member do
      get 'pdf'
    end
  end
  resources :technical_orders do 
    collection do      
      get :history      
    end
    resources :changes
    
  end
  resources :techlogs do 
    member do
      get 'create_addl_log'
      get 'create_limitation_log'
      get 'create_techlog'
      get 'pdf'
      get 'approve_extension'
    end
  end
  resources :work_unit_codes do 
    collection do 
      get 'get_work_unit_codes'
      get :autocomplete_codes
      post :import
      get :upload
    end
  end
  resources :flying_logs do 
    member do
      get 'pdf'
      get 'cancel'
      get 'update_timing'
      get 'release'
      get 'get_history'
    end
  end
  root 'flying_logs#index'
  resources :aircrafts  do 
    collection do 
      get 'get_aircrafts'      
      get 'summary'      
      get 'report'      
    end
    member do 
      post :import
      get :upload
    end
  end
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  mount ActionCable.server => '/cable'

end

app/views/layouts/partials/_footer.html.slim
footer.main-footer.with_out_side_bar
  strong
    a.footer-link href = "/"
      = t :siteheading
  |&nbsp All rights reserved.
.modal.fade.update-modal aria-labelledby="mySmallModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog.modal-sm role="document"     
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  ×
        h4#mySmallModalLabel.modal-title Techlogs Created
      .modal-body
        .update-modal-message
          | 

- flash[:error] = nil

app/views/layouts/partials/_header.html.slim
= link_to root_path, class:'logo' do
  span.logo-mini
    b
      |A
  span.logo-lg
    b
      = current_user.name
= render :partial => "layouts/partials/static_top_bar"

app/views/layouts/partials/_left_side_bar.html.slim
ul.sidebar-menu  
  /- if can? :read, Aircraft
  li class="#{params[:controller] == "aircrafts" ? 'active' : ''}"
    = link_to aircrafts_path do
      .fa.fa-plane
      span.side-bar-heading-text Aircraft
  /- if can? :view_781, Aircraft
    li class="#{params[:controller] == "reports" ? 'active' : ''}"
      a href="#" 
        i.fa.fa-list-ul
        span.side-bar-heading-text Reports
        span.pull-right-container
          i.fa.fa-angle-left.pull-right
      ul.treeview-menu
        li class="#{controller_name == "reports" ? 'active' : ''}"
          = link_to airframe_reports_path do
            .fa.fa-tasks
            span.side-bar-heading-text 781J        
        /li class="#{controller_name == "reports" ? 'active' : ''}"
          = link_to airframe_reports_path do
            .fa.fa-tasks
            span.side-bar-heading-text 781J        
        
  - if can? :read, Inspection
    li class="#{params[:controller] == "inspections" ? 'active' : ''}"
      a href="#" 
        i.fa.fa-list-ul
        span.side-bar-heading-text Inspections
        span.pull-right-container
          i.fa.fa-angle-left.pull-right
      ul.treeview-menu
        li class="#{params[:controller] == "inspections" ? 'active' : ''}"
          = link_to inspections_path(type_cd: 0) do
            .fa.fa-paper-plane 
            span.side-bar-heading-text Aircraft Inspections
        li class="#{params[:controller] == "inspections" ? 'active' : ''}"
          = link_to inspections_path(type_cd: 1) do
            .fa.fa-paper-plane 
            span.side-bar-heading-text Part Inspections        
        - if can? :read, Inspection
          li class="#{params[:controller] == "scheduled_inspections" ? 'active' : ''}"
            = link_to scheduled_inspections_path(status: 1, type: :status) do
              .fa.fa-paper-plane 
              span.side-bar-heading-text Pending Inspections        
          li class="#{params[:controller] == "scheduled_inspections" ? 'active' : ''}"
            = link_to scheduled_inspections_path(status: 4, type: :status) do
              .fa.fa-paper-plane 
              span.side-bar-heading-text Due Inspections        
          li class="#{params[:controller] == "scheduled_inspections" ? 'active' : ''}"
            = link_to scheduled_inspections_path(status: 2, type: :status) do
              .fa.fa-paper-plane 
              span.side-bar-heading-text In Progress Inspections        
          li class="#{params[:controller] == "scheduled_inspections" ? 'active' : ''}"
            = link_to scheduled_inspections_path(condition: 1, type: :condition) do
              .fa.fa-paper-plane 
              span.side-bar-heading-text Extention Applied
          li class="#{params[:controller] == "scheduled_inspections" ? 'active' : ''}"
            = link_to scheduled_inspections_path(condition: 2, type: :condition) do
              .fa.fa-paper-plane 
              span.side-bar-heading-text Extention Granted
  
  - if can? :read, Part
    li class="#{params[:controller] == "parts" ? 'active' : ''}"
      = link_to parts_path do
        .fa.fa-paper-plane 
        span.side-bar-heading-text Parts  
  - if can? :read, Tool
    li class="#{params[:controller] == "tools" ? 'active' : ''}"
      = link_to tools_path do
        .fa.fa-wrench 
        span.side-bar-heading-text Tools
  - if can? :read, RequestedTool
    li class="#{params[:controller] == "requested_tools" ? 'active' : ''}"
      = link_to requested_tools_path do
        .fa.fa-wrench 
        span.side-bar-heading-text Requested Tools
  - if can? :read, User
    li class="#{params[:controller] == "users" ? 'active' : ''}"
      = link_to users_path do
        .fa.fa-user
        span.side-bar-heading-text Users
  - if can? :read, WorkUnitCode
    li class="#{params[:controller] == "work_unit_codes" ? 'active' : ''}"
      = link_to work_unit_codes_path do 
        .fa.fa-chain
        span.side-bar-heading-text Work Unit Codes
  - if can? :read, AutherizationCode
    li class="#{params[:controller] == "autherization_codes" ? 'active' : ''}"
      = link_to autherization_codes_path do 
        .fa.fa-chain
        span.side-bar-heading-text Authorisation Codes
  - if can? :read, TechnicalOrder
    li class="#{params[:controller] == "technical_orders" ? 'active' : ''}"
      a href="#" 
        i.fa.fa-list-ul
        span.side-bar-heading-text DMS Version
        span.pull-right-container
          i.fa.fa-angle-left.pull-right
      ul.treeview-menu
        li class="#{controller_name == "technical_orders" ? 'active' : ''}"
          = link_to history_technical_orders_path do
            .fa.fa-tasks
            span.side-bar-heading-text History        
        li class="#{controller_name == "technical_orders" ? 'active' : ''}"
          = link_to technical_orders_path do
            .fa.fa-folder-open
            span.side-bar-heading-text Technical Orders        
    
  
  - if can? :read, FlyingPlan
    li class="#{params[:controller] == "flying_plans" ? 'active' : ''}"
      = link_to flying_plans_path do 
        .fa.fa-plane
        span.side-bar-heading-text Flying Plan
  - if can? :read, FlyingLog
    li class="#{params[:controller] == "flying_logs" ? 'active' : ''}"
      = link_to flying_logs_path do
        .fa.fa-fighter-jet
        span.side-bar-heading-text Flying Logs
  - if can? :read, Techlog
    li class="#{params[:controller] == "techlogs" ? 'active' : ''}"
      = link_to techlogs_path do
        .fa.fa-anchor
        span.side-bar-heading-text TechLogs
  - if can? :manage_addl_logs, Techlog
    li class="#{params[:controller] == "addl_logs" ? 'active' : ''}"
      = link_to addl_logs_path do
        .fa.fa-exclamation-triangle
        span.side-bar-heading-text ADDL Logs
  - if can? :manage_limitation_log, Techlog
    li class="#{params[:controller] == "limitation_log" ? 'active' : ''}"
      = link_to limitation_logs_path do
        .fa.fa-ban
        span.side-bar-heading-text Limitation Logs
  
  
  

app/views/layouts/partials/_side_bar.html.slim
aside.main-sidebar
  section.sidebar
    = render :partial => 'layouts/partials/left_side_bar'

app/views/layouts/partials/_static_top_bar.html.slim
nav.navbar.navbar-static-top role = "navigation"
  / Sidebar toggle button
  a.sidebar-toggle.with_out_side_bar_top_header data-toggle = "offcanvas" href = "javascript:void(0)"  role = "button"
  - if user_signed_in?
    .navbar-custom-menu
      ul.nav.navbar-nav.navbar-right
        li
          /= link_to edit_user_path(current_user)
          = link_to edit_user_registration_path
            i.fa.fa-key
            | &nbsp;Change your password
        li
          =link_to destroy_user_session_path, :method => :delete do
            i.fa.fa-sign-out
            | &nbsp;Sign-out